<?php

return [
    [
        'name' => 'mode',
        'title' => '类型',
        'type' => 'checkbox',
        'content' => [
            'gallery' => '图像',
            'text' => '随机文字',
            'custom' => '自定义文字',
        ],
        'value' => 'gallery,text',
        'rule' => 'required',
        'msg' => '',
        'tip' => '用于前台显示点选的类型',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'background',
        'title' => '背景图',
        'type' => 'images',
        'content' => [],
        'value' => '/assets/addons/clicaptcha/img/1.png,/assets/addons/clicaptcha/img/2.png,/assets/addons/clicaptcha/img/3.png',
        'rule' => 'required',
        'msg' => '',
        'tip' => '验证码背景图，不少于3张图片，建议长宽为350*233，目前仅支持gif,jpeg,png三种格式',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'font',
        'title' => '字体',
        'type' => 'string',
        'content' => [],
        'value' => '/assets/fonts/SourceHanSansK-Regular.ttf',
        'rule' => 'required',
        'msg' => '',
        'tip' => '验证码字体',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'customtext',
        'title' => '自定义验证文字',
        'type' => 'text',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '一行一个词语<br>建议不超过6个汉字',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'textsize',
        'title' => '点选文字(图像)数量',
        'type' => 'number',
        'content' => [],
        'value' => '4',
        'rule' => 'required',
        'msg' => '',
        'tip' => '点选的文字或图像的数量，建议3-5个',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'disturbsize',
        'title' => '干扰文字(图像)数量',
        'type' => 'number',
        'content' => [],
        'value' => '2',
        'rule' => 'required',
        'msg' => '',
        'tip' => '干扰文字或图像的数量',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'alpha',
        'title' => '验证码透明度',
        'type' => 'number',
        'content' => [],
        'value' => '30',
        'rule' => 'required',
        'msg' => '',
        'tip' => '验证码透明度，0-100，0表示透明,100表示不透明',
        'ok' => '',
        'extend' => '',
    ],
];
