<?php

return [
    [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => 'string',
        'content' => [],
        'value' => '仅支持后台管理，启用深色模式后将忽略后台皮肤设定',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mode',
        'title' => '深色模式',
        'type' => 'radio',
        'group' => '',
        'visible' => '',
        'content' => [
            'auto' => '自动判断深色模式(依赖系统深色设定)',
            'force' => '始终深色模式',
        ],
        'value' => 'auto',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'switchbtn',
        'title' => '切换按钮',
        'type' => 'radio',
        'group' => '',
        'visible' => '',
        'content' => [
            1 => '显示',
            0 => '隐藏',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'customcss',
        'title' => '自定义深色模式样式',
        'type' => 'text',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '如果有未适配的，可以自行添加CSS样式',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'ignoreurllist',
        'title' => '忽略URL列表',
        'type' => 'text',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '如果有未适配的页面，可以添加忽略URL',
        'ok' => '',
        'extend' => '',
    ],
];
